#!/bin/sh
# plot.sh <file(s)>
#	Plot CSV files generated by Sealib RuntimeTest.

ScriptHome=$(dirname $(readlink -e "$0"))

Title="Runtime test"
Files=""
Outfile="runtime-plot.jpg"
Scale="ms"

printHelp() {
	printf "plot.sh [options] <file basename(s)>\n"
	printf "Options:\n"
	printf "\t-t <name>		Title for your plot\n"
	printf "\t-o <file>		Output filename\n"
	printf "\t-s <unit>		Unit of time measure (default: ms)\n"
	printf "\n"
	printf "Example:\nPlot data from standard.csv and efficient.csv in one plot\n"
	printf " -> plot.sh -t 'Algorithm comparison' -o comparison.jpg standard efficient\n"
	exit 0
}
if test $# -eq 0; then
	printHelp
fi

while getopts "t:o:s:h" opt; do
	case $opt in
	t) 
		Title="$OPTARG" 
		printf "Title: $Title\n"
		;;
	o)
		Outfile="$OPTARG"
		;;
	s)
		Scale="$OPTARG"
		;;
	h|?)
		printHelp
		;;
	esac
done
shift $((OPTIND-1))

for file in "$@"; do
	Files="$Files$file "
done
printf "Plotting files: $Files\n"
printf "Output file: $Outfile\n"

gnuplot -e "infiles='$Files'; outfile='$Outfile'; title='$Title'; scale='$Scale'" -c "$ScriptHome/plot_helper.gp"