#!/bin/sh
# plot.sh <file(s)>
#	Plot CSV files generated by Sealib RuntimeTest.

ScriptHome=$(dirname $(readlink -e "$0"))

Title="Runtime test"
Files=""
Outfile="runtime-plot.jpg"

while getopts "t:o:h" opt; do
	case $opt in
	t) 
		Title="$OPTARG" 
		printf "Title: $Title\n"
		;;
	o)
		Outfile="$OPTARG"
		printf "Outfile: $Outfile\n"
		;;
	?)
		printf "plot.sh [options] <file basename(s)>\n"
		printf "Options:\n"
		printf "\t-t <name>		Title for your plot\n"
		printf "\t-o <file>		Output filename\n"
		printf "\n"
		exit 0
		;;
	esac
done
shift $((OPTIND-1))

for file in "$@"; do
	Files="$Files$file "
done
printf "Plotting files: $Files\n"
printf "Output file: $Outfile\n"

gnuplot -e "infiles='$Files'; outfile='$Outfile'; title='$Title'" -c "$ScriptHome/plot_helper.gp"